name: Test MacOS
on:
  push:
    branches:
      - main
      - test
  pull_request:
  workflow_dispatch:
    inputs:
      balVersion:
        default: 2201.3.2
jobs:
  test_linux:
    name: Test action on MacOS
    runs-on: macos-latest
    steps:
      - name: Set env
        run: |-
          echo "balVersion=$(
          if [[${{ github.event.inputs.balVersion }}]]; then
            echo ${{ github.event.inputs.balVersion }}
          else
            echo 2201.3.2
          fi
          )" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: ballerina-platform/setup-ballerina@main
        name: Test the action.
        with:
          version: ${{ env.balVersion }}
      - run: bal version
      - run: bal run hello.bal
