name: Test Windows
on:
  push:
    branches:
      - main
      - test
  pull_request:
  workflow_dispatch:
    inputs:
      balVersion:
        description: "Ballerina Version"
        default: 'latest'
jobs:
  test_windows:
    name: Test action on Windows
    runs-on: windows-latest
    steps:
      - name: Set env
        run: |-
          echo "balVersion=$(
          if [[ -n "${{ inputs.balVersion }}" ]]; then
            echo ${{ inputs.balVersion }}
          else
            echo 2201.3.2
          fi
          )" >> $GITHUB_ENV
        shell: bash
      - uses: actions/checkout@v2
      - uses: Xenowa/setup-ballerina@test
        name: Test the action.
        with:
          version: ${{ env.balVersion }}
      - run: bal version
      - run: bal run hello.bal
